// Generated by scripts/generate_types.mjs from schema/*.json. Do not edit.
// Run `npm run types` after changing a schema; CI fails if this file is stale.

// ---- DesignSystemRecord ----
/**
 * One record per design system / component library in the State of AI in Design Systems study (July 2026). Every affordance, technique and capability carries the source URL of the file it was quoted from.
 */
export interface DesignSystemAIAffordancesRecord {
  /**
   * kebab-case slug, e.g. 'shadcn-ui'
   */
  id: string;
  name: string;
  /**
   * Maintaining org/company
   */
  org?: string;
  /**
   * design-system = tokens+components+guidelines under a brand; component-library = reusable components without a single brand mandate
   */
  category?: 'design-system' | 'component-library' | 'headless-library';
  repo_url?: string;
  docs_url?: string;
  license?: string;
  maintenance: {
    /**
     * version + approx date
     */
    last_release?: string;
    /**
     * commit cadence, open development signals
     */
    activity_note?: string;
    actively_maintained?: boolean;
  };
  /**
   * none = no AI affordances found; emerging = llms.txt or docs page only; invested = official MCP/rules/skills with real engineering behind them; ai-native = AI consumption is a core design goal of the system
   */
  ai_maturity: 'none' | 'emerging' | 'invested' | 'ai-native';
  /**
   * Concrete AI-facing artifacts this system ships
   */
  affordances: {
    type:
      | 'mcp-server'
      | 'llms-txt'
      | 'agents-md'
      | 'claude-md'
      | 'claude-skill'
      | 'cursor-rules'
      | 'copilot-instructions'
      | 'ai-docs-page'
      | 'registry'
      | 'cli-scaffolding'
      | 'figma-code-connect'
      | 'storybook-integration'
      | 'prompt-library'
      | 'codemod-ai'
      | 'other';
    name: string;
    /**
     * shipped by the DS team vs community
     */
    official: boolean;
    /**
     * consumers = people/agents building UIs WITH the system; builders = the DS team maintaining the system itself
     */
    audience: 'consumers' | 'builders' | 'both';
    description: string;
    docs_url?: string;
    /**
     * link to the actual source (prefer raw.githubusercontent / permalink)
     */
    code_url?: string;
    snippet?: {
      language?: string;
      /**
       * verbatim excerpt, <= 40 lines / 1500 chars
       */
      content?: string;
      source_url?: string;
    };
    notes?: string;
  }[];
  /**
   * Model-coercion techniques: how the system forces AI agents to stay on-system instead of inventing components/tokens
   */
  techniques: {
    name: string;
    /**
     * prohibition = explicit negative rules ('never invent components'); tool-gating = agent must call MCP/CLI to obtain source, cannot hallucinate it; curated-context = llms.txt-style condensed docs sized for context windows; validation-loop = linters/type-checkers the agent runs for feedback (e.g. slds-linter); scaffolding = CLIs generate the correct code, agent orchestrates; exemplars = few-shot examples/templates in agent-readable form; token-enforcement = rules/types that force design tokens over raw values; registry-metadata = machine-readable component registry with deps/props; instruction-files = CLAUDE.md/AGENTS.md/rules distributed to repos; design-code-mapping = Figma Code Connect-style node-to-component mapping
     */
    category:
      | 'prohibition'
      | 'tool-gating'
      | 'curated-context'
      | 'validation-loop'
      | 'scaffolding'
      | 'exemplars'
      | 'token-enforcement'
      | 'registry-metadata'
      | 'instruction-files'
      | 'design-code-mapping'
      | 'other';
    description: string;
    snippet?: {
      language?: string;
      content?: string;
      source_url?: string;
    };
  }[];
  platform_integrations?: {
    platform: 'figma' | 'storybook' | 'supernova' | 'knapsack' | 'zeroheight' | 'other';
    description: string;
    url?: string;
  }[];
  building_vs_consumption?: {
    /**
     * 1-3 sentence summary of AI support for using the system
     */
    for_consumers?: string;
    /**
     * 1-3 sentence summary of how the team uses AI to build the system
     */
    for_builders?: string;
  };
  /**
   * what could not be confirmed; open questions
   */
  gaps?: string;
  sources?: string[];
  /**
   * 2-4 sentence editorial summary for the dashboard
   */
  summary: string;
}

// ---- PlatformRecord ----
/**
 * One record per platform in the State of AI in Design Systems study (July 2026). Platforms host or tool design systems rather than being one: Figma, Storybook, Supernova, Knapsack, zeroheight. Each capability carries the URL of the page it was quoted from.
 */
export interface DesignSystemPlatformRecord {
  /**
   * kebab-case slug, e.g. 'zeroheight'
   */
  id: string;
  name: string;
  /**
   * What the platform is, and what it does about AI consumption.
   */
  summary: string;
  /**
   * Prose on who in the study actually uses it. Deliberately not a count: adoption is uneven and partially undocumented, and a number would imply a precision the sources do not support.
   */
  adoption_by_design_systems: string;
  /**
   * Concrete AI-facing capabilities this platform ships. The platform equivalent of a system's affordances, but without `type` and `official`: a platform's capabilities are all first-party by definition, and they do not sort into the affordance taxonomy.
   */
  capabilities: {
    title: string;
    description: string;
    /**
     * Same vocabulary as a system affordance. consumers = people/agents building UIs with the platform; builders = the team maintaining a design system inside it
     */
    audience: 'consumers' | 'builders' | 'both';
    /**
     * The page this capability was read from. Required: this is the basis on which the claim is checkable.
     */
    url: string;
    snippet?: {
      /**
       * Fence label. Extend the list rather than passing an unlabelled string, so the site can highlight consistently.
       */
      language: 'json' | 'markdown' | 'shell' | 'text' | 'ts' | 'tsx';
      /**
       * verbatim excerpt, <= 40 lines / 1500 chars
       */
      content: string;
      source_url: string;
    };
  }[];
  /**
   * Every page consulted for this record, including ones no single capability cites.
   */
  sources: string[];
}

// ---- InsightsRecord ----
/**
 * One paragraph under a page's title. Rendered on both the HTML route and its markdown twin, so it has to read on its own.
 */
export type Lede = string;
/**
 * One string per paragraph. The build joins them; do not embed blank lines.
 *
 * @minItems 1
 */
export type Paragraphs = [string, ...string[]];
/**
 * One string per paragraph. The build joins them; do not embed blank lines.
 *
 * @minItems 1
 */
export type Paragraphs1 = [string, ...string[]];
/**
 * One string per paragraph. The build joins them; do not embed blank lines.
 *
 * @minItems 1
 */
export type Paragraphs2 = [string, ...string[]];

/**
 * The written half of the State of AI in Design Systems study (July 2026): the findings, the essay, the methodology, the caveats, and the per-page ledes. One object, not a collection. Everything here is prose written about the records rather than quoted from a source, which is why nothing in this file carries a source URL.
 */
export interface ReportAnalysisAndCopy {
  /**
   * The home page lede.
   */
  lede: string;
  insights_lede: Lede;
  methodology_lede: Lede;
  techniques_lede: Lede;
  platforms_lede: Lede;
  /**
   * The numbered findings. Order is meaningful: the site numbers them by position, so reordering renumbers them.
   *
   * @minItems 1
   */
  findings: [TitledSection, ...TitledSection[]];
  /**
   * Where the systems agree.
   *
   * @minItems 1
   */
  convergence: [TitledSection, ...TitledSection[]];
  /**
   * Where they do not.
   *
   * @minItems 1
   */
  divergence: [TitledSection, ...TitledSection[]];
  essay: Paragraphs;
  methodology: Paragraphs1;
  caveats: Paragraphs2;
}
export interface TitledSection {
  title: string;
  body: string;
}

// ---- ReadingRecord ----
/**
 * One work on the /reading list of the State of AI in Design Systems study: writing, talks and courses about what happens when a design system meets an AI agent. Unlike the rest of the dataset, this list is not frozen at the July 2026 snapshot — its published date is computed from the newest `added_on` below. Every entry links to a page that was read before it was listed.
 */
export interface FurtherReadingEntry {
  /**
   * kebab-case slug, e.g. 'design-systems-need-evals'. A correction names a record by it, the way a data correction names 'systems/primer-github'.
   */
  id: string;
  /**
   * The work's own title, as the page gives it.
   */
  title: string;
  /**
   * Who made it. A publication rather than a person when the work carries no byline.
   */
  author: string;
  /**
   * ISO date the work was published. Omitted only when the work genuinely has no publication date — a rolling course, or a page that is revised rather than dated.
   */
  published?: string;
  /**
   * What sort of work it is. The list renders these groups in this order, so work reporting data or reading artifacts appears before commentary.
   */
  kind: 'study' | 'essay' | 'talk' | 'course';
  /**
   * The page this entry was read from. Required, and held to the same bar as a record's source_url: a page that loads and shows the thing.
   */
  url: string;
  /**
   * What the work says, on its own terms. Not what it means for this report — a neutral description ages well and needs no claim about this study's own coverage.
   */
  description: string;
  /**
   * A short verbatim line from the work, present when the work has one that does the arguing. Quoted exactly, from the page at `url`.
   */
  quote?: string;
  /**
   * Present when the work costs money. A reading list that sends someone to a checkout without saying so is not serving them.
   */
  price?: {
    /**
     * As the page states it, currency included, e.g. '$995'.
     */
    amount: string;
    /**
     * What that buys, e.g. '20+ hours across six chapters, plus a Slack community'.
     */
    buys: string;
  };
  /**
   * ISO date this entry was added to the list. The newest of these is the list's published last-updated date, which is why it is computed rather than typed.
   */
  added_on: string;
}

// ---- aliases ----
export type DesignSystemRecord = DesignSystemAIAffordancesRecord;
export type PlatformRecord = DesignSystemPlatformRecord;
export type InsightsRecord = ReportAnalysisAndCopy;
export type ReadingRecord = FurtherReadingEntry;

// ---- collections ----
export type DesignSystems = DesignSystemRecord[];
export type Platforms = PlatformRecord[];
export type Reading = ReadingRecord[];
