#!/usr/bin/env node
// Generates types/data.d.ts from schema/*.json.
//
// The schemas are the contract the data must satisfy, so they are the honest
// source for the types too. Hand-written interfaces drift from the schema
// silently; this cannot, because CI regenerates and fails on a diff.
//
// Run with --check to verify the committed file is current without writing.
import { compile } from 'json-schema-to-typescript';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'types', 'data.d.ts');

// `name` is a fallback only: json-schema-to-typescript prefers the schema's own
// `title`, so the emitted interfaces are named after the titles. `alias` is the
// short name the rest of the repo uses, re-exported at the bottom.
const SCHEMAS = [
  {
    file: 'schema/design-system.schema.json',
    name: 'DesignSystemRecord',
    emitted: 'DesignSystemAIAffordancesRecord',
    alias: 'DesignSystemRecord',
  },
  {
    file: 'schema/platform.schema.json',
    name: 'PlatformRecord',
    emitted: 'DesignSystemPlatformRecord',
    alias: 'PlatformRecord',
  },
  {
    file: 'schema/insights.schema.json',
    name: 'InsightsRecord',
    emitted: 'ReportAnalysisAndCopy',
    alias: 'InsightsRecord',
  },
];

const HEADER = `// Generated by scripts/generate_types.mjs from schema/*.json. Do not edit.
// Run \`npm run types\` after changing a schema; CI fails if this file is stale.
`;

const banner = (name) => `\n// ---- ${name} ----\n`;

let body = HEADER;
for (const { file, name } of SCHEMAS) {
  const schema = JSON.parse(readFileSync(join(ROOT, file), 'utf8'));
  const ts = await compile(schema, name, {
    bannerComment: '',
    additionalProperties: false,
    style: { singleQuote: true },
  });
  body += banner(name) + ts;
}

// Short aliases and collection types. The generated interface names come from
// the schema titles and are a mouthful; these are what the .mjs JSDoc uses.
body += '\n// ---- aliases ----\n';
for (const { emitted, alias } of SCHEMAS) {
  body += `export type ${alias} = ${emitted};\n`;
}
body += `
// ---- collections ----
export type DesignSystems = DesignSystemRecord[];
export type Platforms = PlatformRecord[];
`;

// A schema retitled without updating \`emitted\` above would silently emit an
// alias pointing at nothing, so check before writing rather than after.
for (const { emitted, file } of SCHEMAS) {
  if (!body.includes(`export interface ${emitted}`)) {
    console.error(
      `FAIL: expected an interface named ${emitted} from ${file}, but none was emitted.`,
    );
    console.error(
      "The schema's `title` probably changed. Update `emitted` in this script.",
    );
    process.exit(1);
  }
}

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    console.error(`FAIL: ${OUT} does not exist. Run \`npm run types\`.`);
    process.exit(1);
  }
  if (current !== body) {
    console.error(
      'FAIL: types/data.d.ts is stale — a schema changed without regenerating.',
    );
    console.error('Run `npm run types` and commit the result.');
    process.exit(1);
  }
  console.log('types/data.d.ts is current');
} else {
  writeFileSync(OUT, body);
  console.log(
    `wrote ${OUT} (${body.length} bytes) from ${SCHEMAS.length} schemas`,
  );
}
