// Build the Harbor AG-UI Figma plugin: code.js and ui.html next to
// manifest.json, from the templates in src/ and the lab's own modules.
//
//   node figma-plugin/build.mjs            write into figma-plugin/
//   node figma-plugin/build.mjs --out DIR  write into DIR (tests use this)
//
// esbuild is not installed in the lab, and the plugin needs only a handful of
// functions, so this "bundles" by hand, from file text rather than from
// Function.prototype.toString (a minified build would change that text):
//   - code.js gets figmaRuntime, serializeFigmaNode and applyJsonPatch as
//     src/figma/sandbox-tools.js extracts them from src/figma/sandbox.js (it
//     also regenerates src/figma/sandbox-source.js, the copy the Node side and
//     browser bundles use), plus Harbor's compact catalog and variable
//     definitions as JSON.
//   - ui.html gets applyJsonPatch and src/figma/figma-to-tree.js concatenated,
//     its one import and re-export line removed, `export` keywords dropped,
//     and the catalog, tools and context the server's GET /catalog returns.
// Then it checks what it wrote: code.js passes the sandbox syntax guard and
// parses, every inline script in ui.html parses, no template marker survives,
// and the manifest has the fields Figma needs.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { catalogId, catalogToContext, catalogToTools, harbor } from '../src/catalog/index.js';
import { checkSandboxScript, extractSandboxFunctions, writeSandboxSource } from '../src/figma/sandbox-tools.js';
import { compactCatalog, figmaVariableDefs, jsonForSource } from '../src/figma/tree-to-figma.js';

const here = dirname(fileURLToPath(import.meta.url));
const outFlag = process.argv.indexOf('--out');
const out = outFlag > 0 ? resolve(process.argv[outFlag + 1]) : here;

/** @param {string} template @param {Record<string, string>} fills */
function fill(template, fills) {
  let text = template;
  for (const [marker, value] of Object.entries(fills)) {
    if (!text.includes(marker)) throw new Error(`Template marker ${marker} is missing.`);
    // split/join rather than replace: the inlined code is full of `$` patterns.
    text = text.split(marker).join(value);
  }
  return text;
}

/**
 * @param {string} [dir] where to write code.js, ui.html (and manifest.json when not figma-plugin/)
 * @param {{ regenerate?: boolean }} [options] regenerate: also rewrite src/figma/sandbox-source.js (off in tests)
 */
export async function build(dir = out, { regenerate = true } = {}) {
  const [mainTemplate, uiTemplate, figmaToTree, manifestText] = await Promise.all([
    readFile(join(here, 'src/main.js'), 'utf8'),
    readFile(join(here, 'src/ui.html'), 'utf8'),
    readFile(join(here, '../src/figma/figma-to-tree.js'), 'utf8'),
    readFile(join(here, 'manifest.json'), 'utf8'),
  ]);

  const fns = regenerate ? writeSandboxSource() : extractSandboxFunctions();
  const code = fill(mainTemplate, {
    '/*@HARBOR_DATA@*/ null': jsonForSource({ catalogId: catalogId(harbor), catalog: compactCatalog(harbor), variables: figmaVariableDefs() }),
    '/*@APPLY_JSON_PATCH@*/ null': fns.applyJsonPatch,
    '/*@FIGMA_RUNTIME@*/ null': fns.figmaRuntime,
    '/*@SERIALIZE_FIGMA_NODE@*/ null': fns.serializeFigmaNode,
  });
  checkSandboxScript(code, { wrap: false, filename: 'code.js' });

  // figma-to-tree.js may import only the sandbox functions, which are inlined
  // above it; anything else would need a real bundler.
  const imports = [...figmaToTree.matchAll(/^import\s.*$/gm)].map((m) => m[0]);
  if (imports.some((line) => !/from '\.\/sandbox\.js';$/.test(line))) throw new Error(`figma-to-tree.js imports more than ./sandbox.js: ${imports.join(' ')}`);
  const inlined = [
    fns.applyJsonPatch,
    figmaToTree
      .replace(/^import\s.*$/gm, '')
      .replace(/^export\s*\{[^}]*\};?$/gm, '')
      .replace(/^export\s+(?=(async\s+)?function\b|const\b|let\b|class\b)/gm, ''),
  ].join('\n\n');
  if (/^(export|import)\s/m.test(inlined)) throw new Error('figma-to-tree.js has an import or export form build.mjs cannot inline.');
  const ui = fill(uiTemplate, {
    '/*@HARBOR_CLIENT_DATA@*/ null': jsonForSource({ catalog: harbor, tools: catalogToTools(harbor), context: catalogToContext(harbor) }),
    '/*@FIGMA_TO_TREE@*/': inlined.replace(/<\/script/gi, '<\\/script'),
  });
  for (const script of ui.matchAll(/<script>([\s\S]*?)<\/script>/g)) new vm.Script(script[1], { filename: 'ui.html' });

  const manifest = JSON.parse(manifestText);
  const problems = checkManifest(manifest);
  if (problems.length) throw new Error(`manifest.json: ${problems.join('; ')}`);

  await mkdir(dir, { recursive: true });
  await Promise.all([
    writeFile(join(dir, 'code.js'), `// Generated by figma-plugin/build.mjs from figma-plugin/src/main.js. Do not edit.\n${code}`),
    writeFile(join(dir, 'ui.html'), ui),
    dir === here ? Promise.resolve() : writeFile(join(dir, 'manifest.json'), manifestText),
  ]);
  return { dir, codeBytes: Buffer.byteLength(code), uiBytes: Buffer.byteLength(ui), manifest };
}

/** The manifest fields this plugin depends on. */
export function checkManifest(/** @type {any} */ m) {
  const problems = [];
  for (const k of ['name', 'id', 'api', 'main', 'ui']) if (typeof m[k] !== 'string' || !m[k]) problems.push(`${k} is required`);
  if (!Array.isArray(m.editorType) || !m.editorType.includes('figma')) problems.push('editorType must include "figma"');
  if (m.documentAccess !== 'dynamic-page') problems.push('documentAccess must be "dynamic-page"');
  const net = m.networkAccess ?? {};
  for (const k of ['allowedDomains', 'devAllowedDomains']) {
    if (!Array.isArray(net[k]) || !net[k].includes('http://localhost:8787')) problems.push(`networkAccess.${k} must include http://localhost:8787`);
  }
  if (!net.reasoning) problems.push('networkAccess.reasoning is required for localhost domains');
  return problems;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  build()
    .then((r) => console.log(`Built the Harbor AG-UI plugin in ${r.dir}: code.js ${(r.codeBytes / 1024).toFixed(1)} KB, ui.html ${(r.uiBytes / 1024).toFixed(1)} KB.`))
    .catch((error) => {
      console.error(error.message);
      process.exitCode = 1;
    });
}
