// Build the Harbor AG-UI Figma plugin: code.js and ui.html next to
// manifest.json, from the templates in src/ and the lab's own modules.
//
//   node figma-plugin/build.mjs            write into figma-plugin/
//   node figma-plugin/build.mjs --out DIR  write into DIR (tests use this)
//
// esbuild is not installed in the lab, and the plugin needs only a handful of
// functions, so this "bundles" by hand:
//   - code.js gets figmaRuntime, serializeFigmaNode and applyJsonPatch as
//     source text (Function.prototype.toString), plus Harbor's compact catalog
//     and variable definitions as JSON. Those functions are self-contained by
//     design; the same text is what figma_execute receives.
//   - ui.html gets src/figma/figma-to-tree.js inlined with its `export`
//     keywords removed (the module has no imports, and this checks that), and
//     the catalog, tools and context the server's GET /catalog would return.
// Then it checks what it wrote: the main thread parses as a script and avoids
// syntax Figma's sandbox rejects, no template marker survives, and the
// manifest has the fields Figma needs.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { catalogId, catalogToContext, catalogToTools, harbor } from '../src/catalog/index.js';
import { applyJsonPatch, serializeFigmaNode } from '../src/figma/figma-to-tree.js';
import { compactCatalog, figmaRuntime, figmaVariableDefs, jsonForSource, sandboxSource } from '../src/figma/tree-to-figma.js';

const here = dirname(fileURLToPath(import.meta.url));
const outFlag = process.argv.indexOf('--out');
const out = outFlag > 0 ? resolve(process.argv[outFlag + 1]) : here;

/** Syntax the Figma main-thread sandbox rejects (see the Desktop Bridge's own note on optional chaining). */
export const SANDBOX_FORBIDDEN = [
  { re: /\?\./, what: 'optional chaining' },
  { re: /\?\?/, what: 'nullish coalescing' },
  { re: /\{\s*\.\.\.|,\s*\.\.\.\w+\s*[,}]/, what: 'object spread' },
  { re: /catch\s*\{/, what: 'catch without a binding' },
];

/** @param {string} code @param {string} where */
export function checkSandboxSyntax(code, where) {
  for (const { re, what } of SANDBOX_FORBIDDEN) {
    const m = re.exec(code);
    if (m) {
      const line = code.slice(0, m.index).split('\n').length;
      throw new Error(`${where}:${line} uses ${what}, which Figma's plugin sandbox does not run.`);
    }
  }
  new vm.Script(code, { filename: where });
}

/** @param {string} template @param {Record<string, string>} fills */
function fill(template, fills) {
  let text = template;
  for (const [marker, value] of Object.entries(fills)) {
    if (!text.includes(marker)) throw new Error(`Template marker ${marker} is missing.`);
    // split/join rather than replace: the inlined code is full of `$` patterns.
    text = text.split(marker).join(value);
  }
  return text;
}

export async function build(dir = out) {
  const [mainTemplate, uiTemplate, figmaToTree, manifestText] = await Promise.all([
    readFile(join(here, 'src/main.js'), 'utf8'),
    readFile(join(here, 'src/ui.html'), 'utf8'),
    readFile(join(here, '../src/figma/figma-to-tree.js'), 'utf8'),
    readFile(join(here, 'manifest.json'), 'utf8'),
  ]);

  const code = fill(mainTemplate, {
    '/*@HARBOR_DATA@*/ null': jsonForSource({ catalogId: catalogId(harbor), catalog: compactCatalog(harbor), variables: figmaVariableDefs() }),
    '/*@APPLY_JSON_PATCH@*/ null': sandboxSource(applyJsonPatch),
    '/*@FIGMA_RUNTIME@*/ null': sandboxSource(figmaRuntime),
    '/*@SERIALIZE_FIGMA_NODE@*/ null': sandboxSource(serializeFigmaNode),
  });
  checkSandboxSyntax(code, 'code.js');

  if (/^\s*import\s/m.test(figmaToTree)) throw new Error('src/figma/figma-to-tree.js must stay import-free to be inlined into ui.html.');
  const inlined = figmaToTree.replace(/^export\s+(?=(async\s+)?function\b|const\b|let\b|class\b)/gm, '');
  if (/^export\s/m.test(inlined)) throw new Error('figma-to-tree.js has an export form build.mjs cannot inline.');
  const ui = fill(uiTemplate, {
    '/*@HARBOR_CLIENT_DATA@*/ null': jsonForSource({ catalog: harbor, tools: catalogToTools(harbor), context: catalogToContext(harbor) }),
    '/*@FIGMA_TO_TREE@*/': inlined.replace(/<\/script/gi, '<\\/script'),
  });
  for (const script of ui.matchAll(/<script>([\s\S]*?)<\/script>/g)) new vm.Script(script[1], { filename: 'ui.html' });

  const manifest = JSON.parse(manifestText);
  const problems = checkManifest(manifest);
  if (problems.length) throw new Error(`manifest.json: ${problems.join('; ')}`);

  await mkdir(dir, { recursive: true });
  await Promise.all([
    writeFile(join(dir, 'code.js'), `// Generated by figma-plugin/build.mjs from figma-plugin/src/main.js. Do not edit.\n${code}`),
    writeFile(join(dir, 'ui.html'), ui),
    dir === here ? Promise.resolve() : writeFile(join(dir, 'manifest.json'), manifestText),
  ]);
  return { dir, codeBytes: Buffer.byteLength(code), uiBytes: Buffer.byteLength(ui), manifest };
}

/** The manifest fields this plugin depends on. */
export function checkManifest(/** @type {any} */ m) {
  const problems = [];
  for (const k of ['name', 'id', 'api', 'main', 'ui']) if (typeof m[k] !== 'string' || !m[k]) problems.push(`${k} is required`);
  if (!Array.isArray(m.editorType) || !m.editorType.includes('figma')) problems.push('editorType must include "figma"');
  if (m.documentAccess !== 'dynamic-page') problems.push('documentAccess must be "dynamic-page"');
  const net = m.networkAccess ?? {};
  for (const k of ['allowedDomains', 'devAllowedDomains']) {
    if (!Array.isArray(net[k]) || !net[k].includes('http://localhost:8787')) problems.push(`networkAccess.${k} must include http://localhost:8787`);
  }
  if (!net.reasoning) problems.push('networkAccess.reasoning is required for localhost domains');
  return problems;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  build()
    .then((r) => console.log(`Built the Harbor AG-UI plugin in ${r.dir}: code.js ${(r.codeBytes / 1024).toFixed(1)} KB, ui.html ${(r.uiBytes / 1024).toFixed(1)} KB.`))
    .catch((error) => {
      console.error(error.message);
      process.exitCode = 1;
    });
}
